"use client";

import "aws-amplify/auth/enable-oauth-listener";
import { Amplify } from "aws-amplify";
import { parseAmplifyConfig } from "aws-amplify/utils";
import { Hub } from "aws-amplify/utils";
import { useRouter } from "next/navigation";
import { useEffect, useState, type ReactNode } from "react";
import { ensureUserProfile } from "@/lib/auth/profile";
import { hasAmplifyGeo } from "@/lib/map/config";

type AmplifyProviderProps = {
  children: ReactNode;
};

let configured = false;

function isAuthDeployed(outputs: unknown): boolean {
  const poolId = (outputs as { auth?: { user_pool_id?: string } }).auth
    ?.user_pool_id;
  return Boolean(poolId && !poolId.includes("REPLACE"));
}

export function AmplifyProvider({ children }: AmplifyProviderProps) {
  const router = useRouter();
  const [ready, setReady] = useState(configured);

  useEffect(() => {
    if (configured) {
      setReady(true);
      return;
    }

    async function loadConfig() {
      try {
        const mod = await import("@/amplify_outputs.json");
        const outputs = mod.default ?? mod;

        if (isAuthDeployed(outputs) || hasAmplifyGeo(outputs)) {
          const amplifyConfig = parseAmplifyConfig(
            outputs as Parameters<typeof parseAmplifyConfig>[0],
          );
          Amplify.configure(amplifyConfig, { ssr: true });
          configured = true;
        }
      } catch {
        // amplify_outputs.json is generated by `npm run sandbox`
      }
      setReady(true);
    }

    void loadConfig();
  }, []);

  useEffect(() => {
    const unsubscribe = Hub.listen("auth", ({ payload }) => {
      if (payload.event === "signInWithRedirect") {
        void ensureUserProfile()
          .then(() => router.push("/map"))
          .catch((err) => console.error("Profile sync failed", err));
      }
    });
    return unsubscribe;
  }, [router]);

  if (!ready) return null;

  return <>{children}</>;
}
