"use client";

import { Amplify } from "aws-amplify";
import { useEffect, useState, type ReactNode } from "react";
import { hasAmplifyGeo } from "@/lib/map/config";

type AmplifyProviderProps = {
  children: ReactNode;
};

let configured = false;

export function AmplifyProvider({ children }: AmplifyProviderProps) {
  const [ready, setReady] = useState(configured);

  useEffect(() => {
    if (configured) {
      setReady(true);
      return;
    }

    async function loadConfig() {
      try {
        const mod = await import("@/amplify_outputs.json");
        const outputs = mod.default ?? mod;
        if (hasAmplifyGeo(outputs)) {
          Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0], {
            ssr: true,
          });
          configured = true;
        }
      } catch {
        // amplify_outputs.json is generated by `npx ampx sandbox`
      }
      setReady(true);
    }

    void loadConfig();
  }, []);

  if (!ready) return null;

  return <>{children}</>;
}
